ALTER TABLE "StoreSettings"
ADD COLUMN "deliveryPricingMode" TEXT NOT NULL DEFAULT 'FIXED',
ADD COLUMN "baseDeliveryFeeCents" INTEGER NOT NULL DEFAULT 500,
ADD COLUMN "includedDistanceKm" DOUBLE PRECISION NOT NULL DEFAULT 5,
ADD COLUMN "additionalFeePerKmCents" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN "maxDeliveryDistanceKm" DOUBLE PRECISION NOT NULL DEFAULT 5;
